superheroes/mysuperheroes/urls.py
from django.contrib import admin
from django.http import request
from django.urls import path
from . import views


app_name = 'mysuperheroes'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:superhero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='new'),
        path('', views.delete, name='delete')

]

superheroes/superheroes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mysuperheroes/', include('mysuperheroes.urls')),
    path('', RedirectView.as_view(url='/mysuperheroes/'))

]

superheroes/mysuperheroes/models.py
from django.db import models


# Create your models here.


class SuperHero(models.Model):
    objects = None
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=100)


def myfunc():
    print()

superheroes/mysuperheroes/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic.detail import DetailView

from .models import SuperHero


def index(request):
    all_mysuperheroes = SuperHero.objects.all()
    context = {
        'all_mysuperheroes': all_mysuperheroes
    }
    return render(request, 'mysuperheroes/index.html', context)


def detail(request):
    superhero = request.get(pk=1)
    context = {
        'single_superhero': superhero
    }
    return render(request, 'single_superhero/detail.html', context)


def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter')
        primary_ability = request.POST.get('primary')
        secondary_ability = request.POST.get('secondary')
        catch_phrase = request.POST.get('phrase')
        new_superhero = SuperHero(name=name, alter_ego=alter_ego, primary_ability=primary_ability,
                                  secondary_ability=secondary_ability, catch_phrase=catch_phrase)
        new_superhero.save()
        return HttpResponseRedirect(reverse('mysuperheroes:index'))
    else:
        return render(request, 'mysuperheroes/create.html')


def delete(request):
    mysuperheroes = get_object_or_404(SuperHero, id=id)
    if request.method == 'POST':
        mysuperheroes.delete()
        messages.success(request, "successfully deleted")
        return HttpResponseRedirect("/Blog/list")

superheroes/mysuperheroes/templates/mysuperheroes/Robin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<body>
<h1> Black Canary</h1>
<div class="card" style="width: 18rem;">
  <img src="robin.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Robin</h5>
    <p class="card-text">Originally Batman's sidekick, Robin has grown into a Superhero in his own right.</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Alter Ego - Dick Grayson </li>
    <li class="list-group-item">Primary Ability - Superhuman Agility </li>
    <li class="list-group-item">Secondary Ability - Master of Gadgets and Weapons </li>
      <li class="list-group-item">Catch Phrase - "Holy Hard Project, Batman!" </li>
  </ul>

</div>













<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

superheroes/mysuperheroes/templates/mysuperheroes/bigBertha.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<body>
<h1> Black Canary</h1>
<div class="card" style="width: 18rem;">
  <img src="robin.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">BigBertha</h5>
    <p class="card-text">Supermodel by day, Superhero by night..</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Alter Ego - Ashley Crawford </li>
    <li class="list-group-item">Primary Ability - Super Strength </li>
    <li class="list-group-item">Secondary Ability - Ability to alter size and mass of her body </li>
      <li class="list-group-item">Catch Phrase - "Holy Hard Project, Batman!"" </li>
  </ul>

</div>













<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

superheroes/mysuperheroes/templates/mysuperheroes/blackCanary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<body>
<h1> Black Canary</h1>














<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

superheroes/mysuperheroes/templates/mysuperheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<h1>Create a New Superhero!</h1>
<body>

<form action="{% url 'mysuperheroes:new' %}" method="post">
    {% csrf_token %}
    Name:<input type="text" name="name" id="name"><br>
    Alter Ego:<input type="text" name="alter" id="alter"><br>
    Primary Ability:<input type="text" name="primary" id="primary"><br>
    Secondary Ability:<input type="text" name="secondary" id="secondary"><br>
    Catch Phrase<input type="text" name="phrase" id="phrase"><br>
    <input type="submit" value="Add New!">
</form>




</body>
</html>

superheroes/mysuperheroes/templates/mysuperheroes/hellboy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<body>
<h1> Black Canary</h1>
<div class="card" style="width: 18rem;">
  <img src="robin.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Hellboy</h5>
    <p class="card-text">A demon conjured from hell by the Nazis, raised to be a defender of Earth.</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Alter Ego - Anung Un Rama </li>
    <li class="list-group-item">Primary Ability - Superhuman Strength </li>
    <li class="list-group-item">Secondary Ability - Accelerated Healing </li>
      <li class="list-group-item">Catch Phrase - "Aw Crap" </li>
  </ul>

</div>













<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

superheroes/mysuperheroes/templates/mysuperheroes/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Superhero Index</title>
</head>
<body>

<h1>List of Superheroes</h1>
<ul>

       {% for superhero in all_mysuperheroes %}
    <li><h2>{{superhero.name}}</h2>
    <a href="{% url 'mysuperheroes:detail' superhero.id %}">See more info</a></li>
    {% endfor %}

</ul>
<a href="http://127.0.0.1:8000/mysuperheroes/new/" target="_blank">Create a New Superhero!</a>

<ul>
    <h3>Delete a Superhero!</h3>
</ul>

</body>
</html>